import {Volume2,Pause} from 'lucide-react';
import {useEffect,useRef,useState} from 'react';
import {gameRpc,studyPost} from './studyApi';
function ClueAudio({roomId,clue,enabled,active}){
 const audio=useRef(null),[speaking,setSpeaking]=useState(false),[source,setSource]=useState(clue.audio_url||''),[status,setStatus]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{if(!enabled||(!active&&attempt===0))return;let live=true;const controller=new AbortController();let timer;const deadline=Date.now()+45000;
 async function load(){try{setStatus('Preparing audio…');const data=source?{audioUrl:source}:await studyPost('/api/speak',{roomId,clueId:clue.id,mood:'neutral'},controller.signal);if(!live)return;if(data.pending){if(Date.now()>deadline)throw new Error('Audio is taking too long. Tap retry to try again.');timer=setTimeout(load,2500);return;}if(!/^data:audio\/mpeg;base64,[A-Za-z0-9+/]+=*$/.test(data.audioUrl))throw new Error('Audio is unavailable.');setSource(data.audioUrl);audio.current.src=data.audioUrl;try{await audio.current.play();setStatus('Speaking…');}catch{setStatus('Tap play to hear this clue.');}}catch(e){if(live)setStatus(e.message||'Audio unavailable; keep reading.');}}
 void load();return()=>{live=false;controller.abort();clearTimeout(timer);audio.current?.pause();};
 },[enabled,active,clue.id,roomId,attempt]);
 return <span className="read-aloud"><button type="button" className="read-aloud-button" aria-label={speaking?'Pause clue narration':'Play clue narration'} disabled={!source&&!enabled} onClick={()=>{if(!source){setAttempt(n=>n+1);return;}if(!audio.current.paused)audio.current.pause();else audio.current.play().catch(()=>setStatus('Tap play to retry audio.'));}}>{speaking?<Pause size={18}/>:<Volume2 size={18}/>}</button><audio ref={audio} src={source||undefined} data-tutor-audio onPlay={()=>{setSpeaking(true);setStatus('Speaking…');document.querySelectorAll('audio[data-tutor-audio]').forEach(other=>{if(other!==audio.current)other.pause();});}} onPause={()=>{setSpeaking(false);setStatus('Paused');}} onEnded={()=>{setSpeaking(false);setStatus('');}}/><span role="status" className="read-aloud-status">{status}</span></span>;
}
export default function EmberRiddle({roomId,game,userId,seconds,onChange}){
 const [enabled,setEnabled]=useState(false),[buzz,setBuzz]=useState(false),[guess,setGuess]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(event){event.preventDefault();if(busy)return;setBusy(true);try{const correct=await gameRpc('cf_game_guess',{p_room:roomId,p_game:game.id,p_guess:guess});setMessage(correct?'Correct!':'Not quite. Keep listening.');await onChange();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <section className="panel space-y-6"><div className="flex flex-wrap gap-3 items-center"><h2 className="font-display text-2xl">Listen. Connect. Buzz in.</h2><button className="button button-secondary" aria-pressed={enabled} onClick={()=>setEnabled(v=>!v)}>{enabled?'Mute narration':'Enable narration'}</button></div><p className="muted" role="timer">{game.phase==='finished'?'Riddle complete':`Next reveal in ${seconds}s`}</p>
 {(game.clues||[]).map(clue=><section key={clue.id} className="space-y-3"><p className="eyebrow">Clue {clue.order_index+1}</p><p>{clue.text}</p><ClueAudio roomId={roomId} clue={clue} enabled={enabled} active={game.phase!=='finished'&&clue.order_index===game.round_index}/></section>)}
 {game.phase==='finished'?<p role="status"><strong>{game.answer}</strong> — {game.winner?`${game.players.find(p=>p.id===game.winner)?.name||'A teammate'} guessed it first!`:'No correct guess this time.'}</p>:<><button className="button" disabled={!game.participants.includes(userId)} onClick={()=>setBuzz(true)}>Buzz In</button>{buzz&&<form className="space-y-3" onSubmit={submit}><label htmlFor="riddle-guess">Your guess</label><input className="input" id="riddle-guess" maxLength={200} value={guess} onChange={e=>setGuess(e.target.value)}/><button className="button" disabled={busy||!guess.trim()}>Submit guess</button></form>}</>}
 {message&&<p role="status">{message}</p>}</section>;
}
