import {useEffect,useState} from 'react';
import {useOutletContext} from 'react-router-dom';
import {supabase} from '../lib/supabaseClient';
import {studyPost} from '../features/games/studyApi';
import FlipCard from '../features/games/FlipCard';
export default function Flashcards(){const {room}=useOutletContext();return <RoomFlashcards key={room.id} room={room}/>;}
function RoomFlashcards({room}){
 const [topics,setTopics]=useState([]),[cards,setCards]=useState([]),[topic,setTopic]=useState(''),[index,setIndex]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState('');
 async function load(){const result=await supabase.from('flashcards').select('*').eq('room_id',room.id).order('created_at');if(result.error)throw result.error;setCards(result.data);setIndex(0);}
 useEffect(()=>{let live=true;void Promise.all([supabase.from('syllabus_topics').select('id,title').eq('room_id',room.id).order('order_index'),supabase.from('flashcards').select('*').eq('room_id',room.id).order('created_at')]).then(([t,c])=>{if(!live)return;if(t.error||c.error){setError((t.error||c.error).message);return;}setTopics(t.data);setCards(c.data);}).catch(e=>live&&setError(e.message));return()=>{live=false;};},[room.id]);
 const visible=cards.filter(c=>!topic||c.topic_id===topic),current=visible[Math.min(index,visible.length-1)];
 async function generate(){if(busy)return;setBusy(true);setError('');const chosen=topics.filter(t=>!topic||t.id===topic);let done=0;try{for(let i=0;i<chosen.length;i+=1){setProgress(`Generating topics ${i+1}–${Math.min(i+1,chosen.length)} of ${chosen.length}…`);await studyPost('/api/room-study',{roomId:room.id,type:'flashcards',topicIds:chosen.slice(i,i+1).map(t=>t.id)});done=Math.min(i+1,chosen.length);await load();}setProgress('Flashcards saved.');}catch(e){setError(`${e.message} ${done?`${done} topics were already saved; choose remaining topics to retry.`:''}`);setProgress('');}finally{setBusy(false);}}
 function shuffle(){setCards(previous=>{const list=[...previous];for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list;});setIndex(0);}
 return <div className="space-y-6"><header><p className="eyebrow">RECALL AND REPEAT</p><h1 className="font-display page-heading mt-3">Flashcards</h1></header><section className="panel p-5 space-y-3"><label htmlFor="flashcard-topic">Syllabus topic</label><select className="input" id="flashcard-topic" value={topic} onChange={e=>{setTopic(e.target.value);setIndex(0);}} disabled={busy}><option value="">Whole syllabus</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button className="button" disabled={busy||!topics.length} onClick={generate}>{busy?'Generating…':'Generate Flashcards'}</button>{!topics.length&&<p className="muted">Add syllabus topics first.</p>}{progress&&<p role="status">{progress}</p>}{error&&<p role="alert" className="error-banner">{error}</p>}</section>
 {current?<><FlipCard key={current.id} card={current}/><nav className="flex flex-wrap gap-3 items-center" aria-label="Flashcard navigation"><button className="button button-secondary" disabled={index===0} onClick={()=>setIndex(n=>n-1)}>Previous</button><span>{index+1} / {visible.length}</span><button className="button button-secondary" disabled={index>=visible.length-1} onClick={()=>setIndex(n=>n+1)}>Next</button><button className="button button-secondary" onClick={shuffle}>Shuffle</button></nav></>:<p className="empty-state">Generate a set to start reviewing.</p>}</div>;
}
